
INSERT INTO USER_PROFILE (NAME, PASS) VALUES ('admin', 'admin');
INSERT INTO USER_PROFILE (NAME, PASS) VALUES ('user', 'user');

INSERT INTO TODO (USER_ID, TODO_TEXT, DESCRIPTION, DEADLINE) VALUES (1,'test','test','02.11.2024');
INSERT INTO TODO (USER_ID, TODO_TEXT, DESCRIPTION, DEADLINE) VALUES (1,'test2','test2','20.12.2024')


